Implement run_contains for REST API Tests
elastic/elasticsearch-py pull request #1511
Opened 2021-01-14 13:23 UTC by V1NAY8

Partially does #1265 

- Implemented `run_contains` method.
- There is only one example of `yml` file `elasticsearch\rest-api-spec\src\main\resources\rest-api-spec\test\cluster.voting_config_exclusions\10_basic.yml`

@sethmlarson Please review this. Let me know if any changes are required.

2021-01-14 13:24 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-01-21 13:54 UTC, sethmlarson commented
jenkins test this please

2021-01-21 13:58 UTC, sethmlarson requested changes
Thanks for this! Couple of changes for you, if you don't get to them before I do I can manually make commits too :)

2021-01-21 13:58 UTC, sethmlarson commented on .gitignore
> +/.vscode
Let's remove this, instead you can add your editor files into a [global gitignore](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c).

2021-01-21 13:58 UTC, sethmlarson commented on test_elasticsearch/test_server/test_rest_api_spec.py
> +                raise AssertionError(f"{expected} does not match {value}")
The assertation message here could be better, something like `"%s is not contained by %s" % (expected, value)`

Also we can't use f-strings yet for this project, we still support Python <3.6

2021-01-21 19:46 UTC, V1NAY8 commented
Yes, made the changes.

2021-01-21 19:52 UTC, sethmlarson approved these changes
LGTM, thank you!

2021-01-21 19:53 UTC, merged