docs: fix typos
elastic/elasticsearch-py pull request #1576
Opened 2021-04-19 19:32 UTC by pgrimaud

Hello,

This PR will fix : 

- 1 typo in `docs/sphinx/connection.rst`
- 1 typo in `elasticsearch/_async/client/ml.py`
- 1 typo in `elasticsearch/client/ml.py`
- 1 typo in `elasticsearch/connection_pool.py`
- 1 typo in `utils/generate-api.py`

Ciao! :robot:

2021-04-19 19:32 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-04-23 16:54 UTC, sethmlarson commented
Can you remove the changes within `elasticsearch/client` and `elasticsearch/_async/client`? These directories are auto-generated, you'll have to make the typo fixes in the [Elasticsearch repository](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api).

Also you'll need to sign the CLA.

2021-04-23 16:54 UTC, sethmlarson requested changes
Can you remove the changes within `elasticsearch/client` and `elasticsearch/_async/client`? These directories are auto-generated, you'll have to make the typo fixes in the [Elasticsearch repository](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api).

Also you'll need to sign the CLA.

2021-04-26 10:57 UTC, pgrimaud commented
CLA signed (forgot to trigger check) & changes made. 😄

2021-04-26 19:36 UTC, sethmlarson approved these changes

2021-05-25 02:20 UTC, mrbaguvix approved these changes

2021-05-25 12:44 UTC, merged