Add explicit parameters for AIOHttpConnection and AsyncTransport
elastic/elasticsearch-py pull request #1672
Opened 2021-08-06 17:25 UTC by V1NAY8

Closes #1405 

@sethmlarson  take a look at this. Let me know if any changes are required.

2021-08-06 17:25 UTC, elasticmachine commented
Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

2021-08-06 17:28 UTC, V1NAY8 commented
I will fix the tests, probably should pass keyword arguments

2021-08-16 17:19 UTC, sethmlarson requested changes
Thanks for this, almost there! Only the `meta_header` parameter missing.

2021-08-16 17:19 UTC, sethmlarson commented on elasticsearch/_async/transport.py
> +        send_get_body_as="GET",
This is missing a single parameter `meta_header`, can you also add this parameter in `elasticsearch/_async/transport.pyi`?

2021-08-16 17:40 UTC, sethmlarson approved these changes
LGTM, thanks for this! :muscle:

2021-08-16 17:41 UTC, sethmlarson commented
jenkins test this please

2021-08-16 18:36 UTC, merged