[DOCS] Adds a signpost for downloading ES or signing-up for ESS
elastic/elasticsearch-py pull request #2384
Opened 2023-11-24 16:26 UTC by szabosteve

## Overview

This PR adds a signpost to the repo README that links to the ES download page and to the ESS sign-up page.

2023-11-27 06:35 UTC, pquentin requested changes
The README file is (unfortunately) ReST, not Markdown, see https://github.com/elastic/elasticsearch-py/blob/bfa8db26287b5c961a01e7445552a716a5696995/README.rst for the current result.

2023-11-27 07:42 UTC, szabosteve commented on README.rst
> +**for a free trial of Elastic Cloud**.
```suggestion
`**Download the latest version of Elasticsearch** <https://www.elastic.co/downloads/elasticsearch>`_
or
`**sign-up** <https://cloud.elastic.co/registration?elektra=en-ess-sign-up-page>`_
**for a free trial of Elastic Cloud**.
```

2023-11-27 07:58 UTC, szabosteve commented on README.rst
> +**for a free trial of Elastic Cloud**.
```suggestion
`Download the latest version of Elasticsearch <https://www.elastic.co/downloads/elasticsearch>`_
or
`sign-up <https://cloud.elastic.co/registration?elektra=en-ess-sign-up-page>`_
for a free trial of Elastic Cloud.
```

2023-11-28 09:15 UTC, szabosteve commented
@pquentin I addressed your comment via the last commits.

2023-12-01 13:10 UTC, pquentin reviewed
Thanks! What are your thoughts on moving those to the installation sections?

 * README.rst: either remove this or put it just before "Refer to the Installation section"
 * guide: either in https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/getting-started-python.html#_installation or in the installation page itself.
 * sphinx: I think this one works :+1:

2023-12-04 12:05 UTC, pquentin commented
buildkite test this please

2023-12-04 16:30 UTC, szabosteve commented
@elasticmachine test this please

2023-12-04 16:51 UTC, merged